-- Nepal Promise Tracker — database setup
-- Run this ONCE in Supabase: your project -> SQL Editor -> New query -> paste -> Run.
--
-- It creates the promises table, allows public read access (anyone can view),
-- and inserts the same fictional demo rows the app ships with.
-- Adding/editing real entries is done through the Supabase Table Editor.

create table if not exists promises (
  id bigint generated by default as identity primary key,
  politician text not null,
  party text,
  position text,
  promise text not null,
  category text not null default 'Other',
  status text not null default 'in_progress'
    check (status in ('kept', 'broken', 'in_progress')),
  date_made date,
  deadline date,
  evidence text,
  source_url text,
  created_at timestamptz default now()
);

-- Row Level Security: the anon (public) key may READ, but not write.
-- You add/edit rows through the Supabase dashboard, which bypasses this safely.
alter table promises enable row level security;

create policy "Public read access"
  on promises for select
  to anon
  using (true);

-- Demo rows (fictional politicians — replace with sourced, real entries).
insert into promises
  (politician, party, position, promise, category, status, date_made, deadline, evidence, source_url)
values
  ('Ram Bahadur Shrestha (Demo)', 'Demo Party A', 'Minister of Infrastructure (fictional)',
   'Complete the 42 km ring-road expansion within two years of taking office.',
   'Infrastructure', 'in_progress', '2024-03-15', '2026-03-15',
   'Demo entry — construction reported at 60% in sample data.', 'https://example.com/demo-source'),
  ('Sita Kumari Tamang (Demo)', 'Demo Party B', 'Minister of Energy (fictional)',
   'End all scheduled load-shedding in residential areas within 18 months.',
   'Energy', 'kept', '2023-06-01', '2024-12-01',
   'Demo entry — sample data marks this delivered on schedule.', 'https://example.com/demo-source'),
  ('Ram Bahadur Shrestha (Demo)', 'Demo Party A', 'Minister of Infrastructure (fictional)',
   'Repair 500 km of rural roads damaged in the monsoon within one year.',
   'Infrastructure', 'broken', '2023-09-10', '2024-09-10',
   'Demo entry — sample data marks under 100 km completed by deadline.', 'https://example.com/demo-source'),
  ('Krishna Prasad Adhikari (Demo)', 'Demo Party C', 'Minister of Education (fictional)',
   'Provide free internet access to every public school in the district.',
   'Education', 'in_progress', '2024-01-20', '2025-12-31',
   'Demo entry — sample data reports 40% of schools connected.', 'https://example.com/demo-source'),
  ('Maya Devi Gurung (Demo)', 'Demo Party B', 'Minister of Health (fictional)',
   'Open a fully staffed health post in every ward of the municipality.',
   'Health', 'kept', '2022-11-05', '2024-11-05',
   'Demo entry — sample data marks all wards covered.', 'https://example.com/demo-source'),
  ('Krishna Prasad Adhikari (Demo)', 'Demo Party C', 'Minister of Education (fictional)',
   'Hire 2,000 new teachers for public schools before the next academic year.',
   'Education', 'broken', '2023-02-14', '2024-04-01',
   'Demo entry — sample data marks 300 of 2,000 positions filled.', 'https://example.com/demo-source'),
  ('Maya Devi Gurung (Demo)', 'Demo Party B', 'Minister of Health (fictional)',
   'Cut ambulance response time in the valley to under 15 minutes.',
   'Health', 'in_progress', '2024-05-30', '2026-05-30',
   'Demo entry — sample average currently 22 minutes.', 'https://example.com/demo-source'),
  ('Sita Kumari Tamang (Demo)', 'Demo Party B', 'Minister of Energy (fictional)',
   'Bring grid electricity to 100 remote mountain villages.',
   'Energy', 'in_progress', '2023-12-01', '2026-12-01',
   'Demo entry — sample data reports 61 villages connected.', 'https://example.com/demo-source');
